version: 2
updates:
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/packages/nextjs"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  # Enable version updates for Cargo
  - package-ecosystem: "cargo"
    directory: "/packages/server"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "cargo"
    directory: "/packages/zk-mpc-node"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "cargo"
    directory: "/packages/mpc-circuits"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "cargo"
    directory: "/packages/mpc-algebra-wasm"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10